# Copyright <2023> [Copyright rossihwang@gmail.com]

set(TOOLCHAIN_PREFIX $ENV{TOOLCHAIN_PREFIX})

# CMake cross compile settings
set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR riscv)

# Cross compile toolchain settings
message(VERBOSE "TOOLCHAIN_PREFIX: " ${TOOLCHAIN_PREFIX})
set(CROSS_COMPILER riscv-none-embed-)
message(VERBOSE "CROSS_COMPILER: " ${CROSS_COMPILER})

set(TOOLCHAIN_BIN_DIR ${TOOLCHAIN_PREFIX}/bin)

# Compilers settings
set(CMAKE_C_COMPILE_FEATURES -specs=nosys.specs)
set(CMAKE_C_COMPILER ${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILER}gcc)
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILER}g++)
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILER}gcc)

# Skip compiler checking
set(CMAKE_C_COMPILER_WORKS ON)
set(CMAKE_CXX_COMPILER_WORKS ON)

# Other tools settings
set(CMAKE_OBJCOPY ${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILER}objcopy)
set(CMAKE_OBJDUMP ${TOOLCHAIN_BIN_DIR}/${CROSS_COMPILER}objdump)

# Libc settings
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)

